apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ln-eks
  region: us-east-2

vpc:
  id: "vpc-0f8bfa1deb26e661a"
  subnets:
    private:
      us-east-2b:
        id: "subnet-074570ad564e89e8f"
      us-east-2a:
        id: "subnet-03250d27ee6e2c66d"
    public:
      us-east-2b:
        id: "subnet-011eeae51e9acf82e"
      us-east-2a:
        id: "subnet-02d72aca035d60bdd"

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 1
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
